import { GrammarTopicItem } from "./types";

export const INITIAL_GRAMMAR_TOPICS: GrammarTopicItem[] = [
  {
    id: "g-present-perfect",
    code: "PPT-01",
    title: "Thì Hiện Tại Hoàn Thành",
    englishTitle: "Present Perfect Tense",
    part: "Part 5 & 6",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Diễn tả hành động bắt đầu trong quá khứ và vẫn tiếp diễn ở hiện tại, hoặc vừa mới hoàn tất để lại kết quả.",
    formula: "S + have/has + V3/ed + O",
    signalWords: ["since + mốc thời gian", "for + khoảng thời gian", "already", "yet", "recently", "just", "so far", "over the past decade"],
    traps: [
      "Bẫy nhầm lẫn 'since' (mốc) và 'for' (khoảng).",
      "Bẫy từ 'past' trong cụm 'over the past 5 years' - đây là dấu hiệu Hiện Tại Hoàn Thành chứ KHÔNG phải Quá Khứ Đơn.",
      "Chủ ngữ là danh từ số ít hoặc danh từ không đếm được dùng 'has', danh từ số nhiều dùng 'have'.",
    ],
    examples: [
      {
        sentence: "Ms. Emily has managed this regional branch for over five years.",
        translation: "Cô Emily đã quản lý chi nhánh khu vực này được hơn năm năm.",
        analysis: "Có 'for over five years' và chủ ngữ 'Ms. Emily' số ít -> dùng 'has managed'.",
      },
      {
        sentence: "Our engineering team has already completed the performance audit.",
        translation: "Đội ngũ kỹ thuật của chúng tôi đã hoàn thành xong việc kiểm toán hiệu suất.",
        analysis: "'Already' đứng giữa trợ động từ has và V3 completed.",
      },
    ],
    questions: [
      {
        id: "ppt-q1",
        part: "Part 5",
        questionText: "Ms. Emily _______ this regional branch for over five years, achieving record revenue growth each quarter.",
        options: {
          A: "manages",
          B: "has managed",
          C: "will manage",
          D: "is managing",
        },
        correctAnswer: "B",
        explanation: "Dấu hiệu nhận biết 'for over five years' (khoảng thời gian từ quá khứ đến hiện tại) kết hợp với chủ ngữ ngôi thứ ba số ít 'Ms. Emily' đòi hỏi thì Hiện Tại Hoàn Thành: has + V3/ed (has managed).",
        trapNote: "Tránh nhầm với Hiện Tại Đơn (A) khi thấy 'each quarter' ở vế sau; động từ chính của câu gắn với trạng từ thời gian 'for over five years'.",
        translation: "Cô Emily đã quản lý chi nhánh khu vực này được hơn 5 năm, đạt mức tăng trưởng doanh thu kỷ lục mỗi quý.",
        difficulty: "500-750",
      },
      {
        id: "ppt-q2",
        part: "Part 5",
        questionText: "Since the introduction of the automated inventory system, order processing errors _______ by nearly 40 percent.",
        options: {
          A: "have decreased",
          B: "decrease",
          C: "decreased",
          D: "will decrease",
        },
        correctAnswer: "A",
        explanation: "Cấu trúc với 'Since + mốc thời gian/sự kiện': mệnh đề chính bắt buộc chia thì Hiện Tại Hoàn Thành. Chủ ngữ 'errors' là danh từ số nhiều -> 'have decreased'.",
        trapNote: "Bẫy chọn 'decreased' (C) vì thấy chữ 'Since' tạo cảm giác thì quá khứ.",
        translation: "Kể từ khi đưa vào hệ thống kiểm kho tự động, các lỗi xử lý đơn hàng đã giảm gần 40 phần trăm.",
        difficulty: "500-750",
      },
      {
        id: "ppt-q3",
        part: "Part 5",
        questionText: "The external auditing committee has not _______ its annual financial assessment report yet.",
        options: {
          A: "finalize",
          B: "finalizes",
          C: "finalized",
          D: "finalizing",
        },
        correctAnswer: "C",
        explanation: "Sau trợ động từ 'has not', ta cần một quá khứ phân từ V3/ed để tạo thành thể phủ định thì Hiện Tại Hoàn Thành (has not finalized).",
        trapNote: "Từ 'yet' ở cuối câu là dấu hiệu kinh điển của thì Hiện Tại Hoàn Thành.",
        translation: "Ủy ban kiểm toán độc lập vẫn chưa hoàn tất báo cáo đánh giá tài chính hàng năm.",
        difficulty: "350-500",
      },
      {
        id: "ppt-q4",
        part: "Part 6",
        questionText: "Over the past decade, our research facility _______ over thirty patents in renewable energy technologies.",
        options: {
          A: "has registered",
          B: "registers",
          C: "is registering",
          D: "registered",
        },
        correctAnswer: "A",
        explanation: "Cụm từ 'Over the past / last + khoảng thời gian' bắt buộc chia thì Hiện Tại Hoàn Thành. Chủ ngữ 'facility' số ít -> 'has registered'.",
        trapNote: "Nhiều thí sinh thấy chữ 'past' vội chọn Quá Khứ Đơn (D) mà quên cụm 'Over the past decade'.",
        translation: "Trong suốt một thập kỷ qua, cơ sở nghiên cứu của chúng tôi đã đăng ký hơn 30 bằng sáng chế công nghệ năng lượng tái tạo.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 4,
    correctCount: 3,
    wrongCount: 1,
    bookmarked: true,
  },
  {
    id: "g-simple-present",
    code: "SPT-02",
    title: "Thì Hiện Tại Đơn",
    englishTitle: "Simple Present Tense",
    part: "Part 5",
    targetScore: "350-500",
    status: "PUBLISHED",
    summary: "Diễn tả quy định công ty, lịch trình tàu xe cố định, sự thật hiển nhiên hoặc công việc diễn ra thường xuyên.",
    formula: "S + V(s/es) + O | S + am/is/are + Adj/N",
    signalWords: ["always", "usually", "regularly", "on a quarterly basis", "every month", "often", "routinely"],
    traps: [
      "Bẫy danh từ ghép: Chủ ngữ dài có nhiều danh từ, chỉ danh từ chính đứng cuối hoặc trước giới từ mới quyết định chia số ít/nhiều.",
      "Lịch trình giờ giấc của phương tiện giao thông hoặc hội nghị dùng Hiện Tại Đơn thay vì Tương Lai.",
    ],
    examples: [
      {
        sentence: "The compliance team reviews internal regulations on a quarterly basis.",
        translation: "Đội ngũ tuân thủ xem xét các quy định nội bộ theo định kỳ hàng quý.",
        analysis: "Chủ ngữ 'team' số ít, trạng ngữ 'on a quarterly basis' -> reviews.",
      },
    ],
    questions: [
      {
        id: "spt-q1",
        part: "Part 5",
        questionText: "The corporate compliance department _______ internal safety regulations on a quarterly basis.",
        options: {
          A: "review",
          B: "reviews",
          C: "reviewed",
          D: "is reviewing",
        },
        correctAnswer: "B",
        explanation: "Cụm 'on a quarterly basis' (định kỳ mỗi quý) chỉ tính quy luật lặp lại. Chủ ngữ 'department' là danh từ số ít nên thêm 's': reviews.",
        trapNote: "Bẫy danh từ ghép: 'corporate compliance department' có từ cốt lõi là 'department' số ít.",
        translation: "Bộ phận tuân thủ doanh nghiệp đánh giá lại các quy định an toàn nội bộ theo định kỳ hàng quý.",
        difficulty: "350-500",
      },
      {
        id: "spt-q2",
        part: "Part 5",
        questionText: "Direct express trains to Frankfurt usually _______ from Platform 4 at 07:15 AM every weekday.",
        options: {
          A: "depart",
          B: "departs",
          C: "departed",
          D: "departing",
        },
        correctAnswer: "A",
        explanation: "Lịch trình tàu xe cố định chia Hiện Tại Đơn. Chủ ngữ 'Direct express trains' là số nhiều -> động từ nguyên mẫu: depart.",
        trapNote: "Chú ý đuôi danh từ số nhiều '-s' của trains.",
        translation: "Các chuyến tàu tốc hành trực tiếp tới Frankfurt thường khởi hành từ Ga số 4 lúc 7:15 sáng mỗi ngày trong tuần.",
        difficulty: "350-500",
      },
    ],
    studiedCount: 2,
    correctCount: 2,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-simple-past",
    code: "PST-03",
    title: "Thì Quá Khứ Đơn",
    englishTitle: "Simple Past Tense",
    part: "Part 5 & 6",
    targetScore: "350-500",
    status: "PUBLISHED",
    summary: "Diễn tả sự kiện, giao dịch hoặc cuộc họp đã chấm dứt hoàn toàn trong quá khứ với mốc thời gian xác định rõ.",
    formula: "S + V2/ed + O | S + was/were + Adj/N",
    signalWords: ["yesterday", "last week/month/year", "ago", "in + năm quá khứ", "previously", "formerly"],
    traps: [
      "Bẫy từ 'found': 'found' vừa là V2 của 'find' (tìm kiếm), vừa là V nguyên mẫu của 'found' (thành lập -> quá khứ là founded).",
      "Không dùng Hiện Tại Hoàn Thành khi đã có mốc thời gian quá khứ rõ ràng như 'yesterday' hay 'in 2022'.",
    ],
    examples: [
      {
        sentence: "The executive board approved the commercial merger agreement yesterday afternoon.",
        translation: "Ban điều hành đã phê duyệt thỏa thuận sáp nhập thương mại vào chiều hôm qua.",
        analysis: "Có 'yesterday afternoon' -> động từ chia approved.",
      },
    ],
    questions: [
      {
        id: "pst-q1",
        part: "Part 5",
        questionText: "The executive board _______ the commercial merger agreement during yesterday afternoon's session.",
        options: {
          A: "approved",
          B: "approves",
          C: "will approve",
          D: "has approved",
        },
        correctAnswer: "A",
        explanation: "Có mốc thời gian xác định 'yesterday afternoon's session' nên chia Quá Khứ Đơn: approved.",
        trapNote: "Không chọn Hiện Tại Hoàn Thành (D) khi có 'yesterday'.",
        translation: "Ban điều hành đã phê duyệt thỏa thuận sáp nhập thương mại trong phiên họp chiều hôm qua.",
        difficulty: "350-500",
      },
      {
        id: "pst-q2",
        part: "Part 5",
        questionText: "Three years ago, Dr. Jensen _______ the pharmaceutical startup that later pioneered this vaccine.",
        options: {
          A: "founded",
          B: "funds",
          C: "found",
          D: "founding",
        },
        correctAnswer: "A",
        explanation: "'Three years ago' yêu cầu thì Quá Khứ Đơn. Động từ 'found' (thành lập công ty) có quá khứ là 'founded'.",
        trapNote: "Tránh nhầm với 'found' là dạng quá khứ của 'find' (tìm thấy).",
        translation: "Ba năm trước, Tiến sĩ Jensen đã thành lập công ty khởi nghiệp dược phẩm mà sau này tiên phong phát triển loại vắc-xin này.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 2,
    correctCount: 2,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-simple-future",
    code: "SFT-04",
    title: "Thì Tương Lai & Mệnh Đề Thời Gian",
    englishTitle: "Future Tenses & Time Clauses",
    part: "Part 5",
    targetScore: "350-500",
    status: "PUBLISHED",
    summary: "Diễn tả kế hoạch dự kiến hoặc cam kết trong tương lai; quy tắc phối thì mệnh đề chỉ thời gian (when, as soon as, once).",
    formula: "S + will + V_inf | Mệnh đề chính (will + V) + as soon as + Mệnh đề thời gian (Hiện tại đơn)",
    signalWords: ["tomorrow", "next week", "soon", "shortly", "in the upcoming days", "as soon as", "once"],
    traps: [
      "Bẫy phối thì kinh điển: Trong mệnh đề trạng ngữ chỉ thời gian bắt đầu bằng 'when/as soon as/after', TUYỆT ĐỐI không dùng 'will'.",
      "Sau 'will' bắt buộc là động từ nguyên mẫu không chia to.",
    ],
    examples: [
      {
        sentence: "We will dispatch your order as soon as the wire transfer confirmation is received.",
        translation: "Chúng tôi sẽ gửi đơn hàng ngay khi nhận được xác nhận chuyển khoản.",
        analysis: "Vế chính dùng 'will dispatch', vế sau 'as soon as' dùng hiện tại đơn 'is received'.",
      },
    ],
    questions: [
      {
        id: "sft-q1",
        part: "Part 5",
        questionText: "We _______ your expedited shipment as soon as the wire transfer confirmation is verified.",
        options: {
          A: "will dispatch",
          B: "dispatched",
          C: "dispatch",
          D: "have dispatched",
        },
        correctAnswer: "A",
        explanation: "Cấu trúc mệnh đề trạng ngữ chỉ thời gian: Mệnh đề chính (Tương lai đơn: will dispatch) + as soon as + Mệnh đề thời gian (Hiện tại đơn: is verified).",
        trapNote: "'Will' chỉ đứng ở mệnh đề chính, không đứng trong mệnh đề chứa 'as soon as'.",
        translation: "Chúng tôi sẽ gửi kiện hàng hỏa tốc ngay khi xác nhận chuyển khoản được kiểm chứng.",
        difficulty: "500-750",
      },
      {
        id: "sft-q2",
        part: "Part 5",
        questionText: "The technical maintenance crew _______ the servers late tonight to minimize downtime.",
        options: {
          A: "will restart",
          B: "restarted",
          C: "have restarted",
          D: "restarting",
        },
        correctAnswer: "A",
        explanation: "'Late tonight' (đêm muộn hôm nay) chỉ hành động sắp diễn ra trong tương lai -> will restart.",
        trapNote: "Phân biệt với 'last night' (tối qua).",
        translation: "Đội bảo trì kỹ thuật sẽ khởi động lại các máy chủ vào đêm muộn hôm nay để giảm thiểu gián đoạn.",
        difficulty: "350-500",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-passive-voice",
    code: "PV-05",
    title: "Câu Bị Động Trong Hợp Đồng & Quy Chế",
    englishTitle: "Passive Voice in Business English",
    part: "Part 5 & 6",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Được dùng khi đối tượng chịu tác động quan trọng hơn chủ thể hành động. Rất phổ biến trong thông báo chính sách, tài liệu bảo mật và văn bản hợp đồng.",
    formula: "S + be + V3/ed (+ by O) | Modal: S + modal + be + V3/ed",
    signalWords: ["by + tân ngữ", "must be + V3/ed", "has been + V3/ed", "is scheduled to be + V3/ed"],
    traps: [
      "Bẫy trạng từ xen giữa: has been [completely] revised. Trạng từ đứng xen giữa 'be' và 'V3/ed' để bổ nghĩa.",
      "Chủ ngữ là vật (báo cáo, đơn hàng, gói cước) hầu như luôn đi với câu bị động nếu phía sau không có tân ngữ trực tiếp.",
    ],
    examples: [
      {
        sentence: "All confidential financial statements must be reviewed before publication.",
        translation: "Tất cả các báo cáo tài chính mật phải được xem xét kỹ lưỡng trước khi xuất bản.",
        analysis: "Modal passive: must be reviewed.",
      },
    ],
    questions: [
      {
        id: "pv-q1",
        part: "Part 5",
        questionText: "All confidential financial statements must be _______ by the certified public accountant before publication.",
        options: {
          A: "reviewed",
          B: "review",
          C: "reviewing",
          D: "reviews",
        },
        correctAnswer: "A",
        explanation: "Cấu trúc bị động với động từ khuyết thiếu: Modal Verb (must) + be + V3/ed (reviewed). Báo cáo tài chính chịu tác động hành động xem xét.",
        trapNote: "Có 'by the accountant' là dấu hiệu điển hình của câu bị động.",
        translation: "Tất cả các báo cáo tài chính mật phải được xem xét kỹ lưỡng bởi kế toán viên công chứng trước khi xuất bản.",
        difficulty: "350-500",
      },
      {
        id: "pv-q2",
        part: "Part 6",
        questionText: "The employee handbook has been completely _______ to reflect current remote work protocols.",
        options: {
          A: "revised",
          B: "revising",
          C: "revise",
          D: "revision",
        },
        correctAnswer: "A",
        explanation: "Cấu trúc bị động thì Hiện Tại Hoàn Thành: has been + (trạng từ completely) + V3/ed (revised). 'Sổ tay nhân viên' được sửa đổi.",
        trapNote: "Trạng từ 'completely' đứng xen giữa để gây rối mắt thí sinh.",
        translation: "Cuốn sổ tay nhân viên đã được sửa đổi toàn diện nhằm phản ánh đúng các quy trình làm việc từ xa hiện hành.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 2,
    correctCount: 2,
    wrongCount: 0,
    bookmarked: true,
  },
  {
    id: "g-conditionals",
    code: "CS-06",
    title: "Câu Điều Kiện & Đảo Ngữ Với Should/Had",
    englishTitle: "Conditionals & Inversion in TOEIC",
    part: "Part 5",
    targetScore: "750+",
    status: "PUBLISHED",
    summary: "Câu điều kiện loại 1, 2, 3 và kỹ thuật Đảo ngữ câu điều kiện cực kỳ phổ biến trong các câu hỏi điểm 700+ TOEIC Part 5.",
    formula: "Loại 1: If + S + V(hiện tại), S + will + V | Đảo ngữ loại 1: Should + S + V_inf, S + will/please + V",
    signalWords: ["If", "Provided that", "As long as", "Should you require", "Had we known", "Unless (= If not)"],
    traps: [
      "Bẫy đảo ngữ Should: 'Should you have any questions...' đứng đầu câu không phải câu hỏi mà là câu điều kiện đảo ngữ mang nghĩa 'Nếu bạn có bất kỳ câu hỏi nào...'. Động từ sau 'Should + S' luôn ở dạng NGUYÊN THỂ.",
      "Unless đã mang nghĩa phủ định, mệnh đề sau Unless không dùng dạng phủ định.",
    ],
    examples: [
      {
        sentence: "Should you require any further assistance with your travel itinerary, please contact our help desk.",
        translation: "Nếu quý khách cần thêm bất kỳ sự hỗ trợ nào về lịch trình, xin vui lòng liên hệ bàn hỗ trợ của chúng tôi.",
        analysis: "Đảo ngữ loại 1: Should + you + require (V_inf).",
      },
    ],
    questions: [
      {
        id: "cs-q1",
        part: "Part 5",
        questionText: "Should you _______ any further assistance with your travel itinerary, please contact our help desk.",
        options: {
          A: "require",
          B: "requires",
          C: "required",
          D: "requiring",
        },
        correctAnswer: "A",
        explanation: "Đảo ngữ câu điều kiện loại 1: Đưa 'Should' lên đầu câu thay cho 'If', động từ theo sau luôn ở dạng NGUYÊN THỂ KHÔNG TO (Should + S + V_inf). Chọn 'require'.",
        trapNote: "Bẫy kinh điển: Thí sinh tưởng 'Should' là trợ động từ câu hỏi hoặc chia theo ngôi mà chọn sai.",
        translation: "Nếu quý khách cần thêm bất kỳ sự hỗ trợ nào về lịch trình, xin vui lòng liên hệ bàn hỗ trợ của chúng tôi.",
        difficulty: "750+",
      },
      {
        id: "cs-q2",
        part: "Part 5",
        questionText: "If the client _______ the revised proposal by Friday, we will immediately initiate the development phase.",
        options: {
          A: "approves",
          B: "approved",
          C: "will approve",
          D: "approving",
        },
        correctAnswer: "A",
        explanation: "Câu điều kiện loại 1: Mệnh đề If chia ở thì Hiện Tại Đơn (approves), mệnh đề chính chia ở Tương Lai Đơn (will initiate). Chủ ngữ 'the client' số ít -> 'approves'.",
        trapNote: "Tuyệt đối không dùng 'will' trong mệnh đề If.",
        translation: "Nếu khách hàng phê duyệt đề xuất đã chỉnh sửa trước thứ Sáu, chúng tôi sẽ ngay lập tức khởi động giai đoạn phát triển.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 2,
    correctCount: 1,
    wrongCount: 1,
    bookmarked: true,
  },
  {
    id: "g-relative-clauses",
    code: "RC-07",
    title: "Mệnh Đề Quan Hệ & Rút Gọn Mệnh Đề",
    englishTitle: "Relative Clauses & Reduced Participles",
    part: "Part 5 & 6",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Đại từ quan hệ (who, whom, which, whose, that) và kỹ thuật Rút gọn mệnh đề quan hệ dạng V-ing (chủ động) / V-ed (bị động).",
    formula: "N(người) + who + V | N(sở hữu) + whose + N | Rút gọn: N + V-ing (chủ động) / V-ed (bị động)",
    signalWords: ["who", "whom", "which", "whose", "those who", "the candidate who", "all items purchased"],
    traps: [
      "Bẫy whose: Nếu sau chỗ trống là một DANH TỪ không có mạo từ (a/an/the) thì gần như 100% chọn 'whose'.",
      "Bẫy rút gọn mệnh đề: Câu đã có động từ chính, động từ bổ nghĩa đứng sau danh từ phải rút gọn thành V-ing hoặc V-ed.",
    ],
    examples: [
      {
        sentence: "Job applicants who possess at least three years of project management experience will be prioritized.",
        translation: "Các ứng viên sở hữu ít nhất ba năm kinh nghiệm quản lý dự án sẽ được ưu tiên.",
        analysis: "Who làm chủ ngữ thay thế cho Job applicants.",
      },
      {
        sentence: "Please direct your inquiries to the department supervisor whose office is on the fourth floor.",
        translation: "Xin vui lòng gửi thắc mắc tới giám sát bộ phận, người có văn phòng ở tầng 4.",
        analysis: "Whose office: văn phòng của giám sát đó.",
      },
    ],
    questions: [
      {
        id: "rc-q1",
        part: "Part 5",
        questionText: "Job applicants _______ possess at least three years of project management experience will be prioritized.",
        options: {
          A: "who",
          B: "whom",
          C: "which",
          D: "whose",
        },
        correctAnswer: "A",
        explanation: "Đại từ quan hệ thay thế cho danh từ chỉ người 'Job applicants' và làm CHỦ NGỮ trước động từ 'possess' phải là 'who'.",
        trapNote: "Không dùng 'whom' vì sau 'whom' phải là mệnh đề S + V (tân ngữ).",
        translation: "Các ứng viên sở hữu ít nhất ba năm kinh nghiệm quản lý dự án sẽ được ưu tiên xem xét.",
        difficulty: "350-500",
      },
      {
        id: "rc-q2",
        part: "Part 5",
        questionText: "Please direct your inquiries to the department supervisor _______ office is on the fourth floor.",
        options: {
          A: "whose",
          B: "who",
          C: "which",
          D: "whom",
        },
        correctAnswer: "A",
        explanation: "Đại từ quan hệ chỉ sở hữu: N(người) + WHOSE + N(vật sở hữu). 'whose office' = văn phòng của người giám sát đó.",
        trapNote: "Nhận biết: 'office' đứng ngay sau khoảng trống không có mạo từ a/the -> chọn 'whose'.",
        translation: "Xin vui lòng gửi thắc mắc của bạn tới người giám sát bộ phận, người có văn phòng làm việc ở tầng bốn.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-subject-verb-agreement",
    code: "SVA-08",
    title: "Hòa Hợp Chủ Ngữ & Động Từ",
    englishTitle: "Subject-Verb Agreement",
    part: "Part 5",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Quy tắc xác định danh từ chính để chia động từ số ít hoặc số nhiều. Cảnh giác với cụm giới từ xen giữa và các đại từ bất định.",
    formula: "The N1 + prep + N2 -> Động từ chia theo N1! | Either... or / Neither... nor -> Động từ chia theo S gần nhất!",
    signalWords: ["The delivery of raw materials IS...", "Each/Every + N số ít -> V số ít", "Neither... nor", "A variety of + Ns -> V số nhiều"],
    traps: [
      "Bẫy danh từ gần kề: Thí sinh thấy danh từ số nhiều đứng ngay trước chỗ trống (sau giới từ of/in) liền vội chia số nhiều.",
      "Phân biệt: 'The variety of + Ns' -> V số ít; còn 'A variety of + Ns' -> V số nhiều.",
    ],
    examples: [
      {
        sentence: "The delivery of raw materials to the manufacturing plants has been delayed due to customs inspections.",
        translation: "Việc giao nguyên liệu thô đến các nhà máy sản xuất đã bị trì hoãn do kiểm tra hải quan.",
        analysis: "Chủ ngữ chính là 'The delivery' (số ít) -> has been delayed.",
      },
    ],
    questions: [
      {
        id: "sva-q1",
        part: "Part 5",
        questionText: "The delivery of raw materials to the manufacturing plants _______ delayed due to customs inspections.",
        options: {
          A: "has been",
          B: "have been",
          C: "are",
          D: "were",
        },
        correctAnswer: "A",
        explanation: "Danh từ đứng trước giới từ 'of' là 'The delivery' (số ít), các thành phần sau chỉ là bổ ngữ. Do đó động từ chia số ít: 'has been'.",
        trapNote: "Bẫy danh từ gần kề: 'plants' hay 'materials' số nhiều nằm ngay trước chỗ trống để đánh lừa thị giác.",
        translation: "Việc giao nguyên liệu thô đến các nhà máy sản xuất đã bị trì hoãn do kiểm tra hải quan.",
        difficulty: "500-750",
      },
      {
        id: "sva-q2",
        part: "Part 5",
        questionText: "Neither the regional manager nor the sales representatives _______ aware of the sudden policy change.",
        options: {
          A: "were",
          B: "was",
          C: "is",
          D: "has been",
        },
        correctAnswer: "A",
        explanation: "Quy tắc 'Neither... nor...': Động từ chia theo CHỦ NGỮ GẦN NHẤT. Chủ ngữ gần nhất là 'the sales representatives' (số nhiều) -> dùng 'were'.",
        trapNote: "Nhiều người nhìn 'manager' ở vế trước rồi chọn 'was' là sai quy tắc gần nhất.",
        translation: "Cả người quản lý khu vực lẫn các đại diện bán hàng đều không hay biết về sự thay đổi chính sách đột ngột.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-conjunctions-prepositions",
    code: "CP-09",
    title: "Phân Biệt Liên Từ & Giới Từ",
    englishTitle: "Conjunctions vs Prepositions",
    part: "Part 5",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Phân biệt liên từ (nối mệnh đề có S + V: Although, Because, While) và giới từ (nối cụm danh từ/V-ing: Despite, Because of, During).",
    formula: "Liên từ + S + V | Giới từ + Noun Phrase / V-ing",
    signalWords: ["Although vs Despite", "Because vs Due to / Because of", "While vs During", "By vs Until"],
    traps: [
      "Bẫy cấu trúc: Thấy danh từ dài có tính từ bổ nghĩa phía sau tưởng là mệnh đề, chọn Although thay vì Despite.",
      "Phân biệt 'by' (hoàn thành trước thời hạn deadline) và 'until' (hành động duy trì liên tục đến mốc giờ).",
    ],
    examples: [
      {
        sentence: "Despite torrential downpours, the corporate charity marathon was conducted on schedule.",
        translation: "Mặc dù mưa như trút nước, cuộc chạy marathon từ thiện của công ty vẫn diễn ra đúng tiến độ.",
        analysis: "Sau chỗ trống là cụm danh từ 'torrential downpours' -> dùng giới từ Despite.",
      },
    ],
    questions: [
      {
        id: "cp-q1",
        part: "Part 5",
        questionText: "_______ torrential downpours, the corporate charity marathon was conducted on schedule.",
        options: {
          A: "Despite",
          B: "Although",
          C: "Even though",
          D: "In spite",
        },
        correctAnswer: "A",
        explanation: "Sau chỗ trống là cụm danh từ 'torrential downpours'. Để chỉ sự tương phản đi với cụm danh từ, dùng giới từ 'Despite'.",
        trapNote: "'Although' và 'Even though' phải đi với mệnh đề (S + V). 'In spite' thiếu chữ 'of'.",
        translation: "Mặc dù trời mưa như trút nước, cuộc chạy marathon từ thiện của công ty vẫn được diễn ra đúng tiến độ.",
        difficulty: "500-750",
      },
      {
        id: "cp-q2",
        part: "Part 5",
        questionText: "The final revisions to the construction blueprint must be submitted _______ 5:00 PM on Friday.",
        options: {
          A: "by",
          B: "until",
          C: "during",
          D: "while",
        },
        correctAnswer: "A",
        explanation: "Giới từ 'by' diễn tả hành động hoàn tất muộn nhất vào một thời hạn cụ thể (trước 5h chiều). 'Until' dùng cho hành động kéo dài liên tục.",
        trapNote: "Nộp bài là hành động hoàn tất dứt điểm tại một thời điểm nên dùng 'by'.",
        translation: "Các bản sửa đổi cuối cùng cho bản vẽ xây dựng phải được nộp trước 5 giờ chiều thứ Sáu.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: true,
  },
  {
    id: "g-gerund-infinitive",
    code: "GI-10",
    title: "Danh Động Từ & Động Từ Nguyên Mẫu",
    englishTitle: "Gerunds (V-ing) & Infinitives (To-V)",
    part: "Part 5",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Quy tắc sử dụng V-ing hoặc To-V sau các động từ và cụm thành ngữ đặc thù trong văn phong công sở tiếng Anh.",
    formula: "Verb + V-ing: postpone, consider, avoid, finish | Verb + To-V: decide, plan, agree, hesitate",
    signalWords: ["look forward to + V-ing", "be committed to + V-ing", "consider + V-ing", "hesitate to + V", "aim to + V"],
    traps: [
      "Bẫy chữ 'to': Nhiều người thấy 'to' trong 'look forward to' hoặc 'be committed to' liền chia V nguyên mẫu, nhưng 'to' ở đây là giới từ nên bắt buộc theo sau là V-ing!",
    ],
    examples: [
      {
        sentence: "The management committee is considering implementing a new flexible hybrid work schedule.",
        translation: "Ủy ban quản lý đang cân nhắc áp dụng một lịch làm việc kết hợp linh hoạt mới.",
        analysis: "Consider + V-ing -> implementing.",
      },
    ],
    questions: [
      {
        id: "gi-q1",
        part: "Part 5",
        questionText: "The management committee is considering _______ a new flexible hybrid work schedule starting next month.",
        options: {
          A: "implementing",
          B: "to implement",
          C: "implement",
          D: "implemented",
        },
        correctAnswer: "A",
        explanation: "Động từ 'consider' theo sau bắt buộc là Danh động từ V-ing (consider doing something: cân nhắc làm gì). Chọn 'implementing'.",
        trapNote: "Nhiều người nghĩ 'cân nhắc để làm' nên chọn 'to implement', nhưng theo quy tắc chuẩn là consider + V-ing.",
        translation: "Ủy ban quản lý đang cân nhắc áp dụng lịch trình làm việc kết hợp linh hoạt mới từ tháng sau.",
        difficulty: "500-750",
      },
      {
        id: "gi-q2",
        part: "Part 5",
        questionText: "The logistics provider agreed _______ full compensation for all merchandise damaged during transit.",
        options: {
          A: "to provide",
          B: "providing",
          C: "provide",
          D: "provision",
        },
        correctAnswer: "A",
        explanation: "Cấu trúc 'agree to do something' (đồng ý làm gì) đòi hỏi động từ nguyên mẫu có 'to' -> 'to provide'.",
        trapNote: "'Agree' đi với 'to V', không đi với V-ing.",
        translation: "Nhà cung cấp dịch vụ hậu cần đã đồng ý bồi thường toàn bộ cho số hàng hóa bị hư hỏng trong quá trình vận chuyển.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-comparatives",
    code: "CMP-11",
    title: "So Sánh Tính Từ & Trạng Từ",
    englishTitle: "Comparatives & Superlatives",
    part: "Part 5",
    targetScore: "500-750",
    status: "PUBLISHED",
    summary: "Cấu trúc so sánh hơn, so sánh nhất và các trạng từ nhấn mạnh mức độ so sánh cực hay thi trong TOEIC (much, significantly, far).",
    formula: "Adj-er / More + Adj + THAN | THE + Adj-est / Most + Adj | Trạng từ nhấn mạnh: significantly/much + more...",
    signalWords: ["than", "the most", "significantly more", "much better", "as... as", "one of the most"],
    traps: [
      "Bẫy trạng từ bổ nghĩa so sánh hơn: Chỉ có các từ như 'much, far, significantly, considerably' mới được đứng trước so sánh hơn, KHÔNG dùng 'very' trước so sánh hơn.",
    ],
    examples: [
      {
        sentence: "This new inventory software is significantly more efficient than the previous version.",
        translation: "Phần mềm kiểm kho mới này hiệu quả hơn đáng kể so với phiên bản trước.",
        analysis: "Significantly bổ nghĩa cho so sánh hơn 'more efficient'.",
      },
    ],
    questions: [
      {
        id: "cmp-q1",
        part: "Part 5",
        questionText: "This new inventory software is _______ more efficient than the previous enterprise version.",
        options: {
          A: "significantly",
          B: "very",
          C: "too",
          D: "extreme",
        },
        correctAnswer: "A",
        explanation: "Để bổ nghĩa và nhấn mạnh cho cấp so sánh hơn ('more efficient than'), ta dùng các trạng từ như 'significantly', 'much', 'far', 'substantially'. Không dùng 'very' trước so sánh hơn.",
        trapNote: "Bẫy từ 'very' rất phổ biến ở thí sinh mức 500.",
        translation: "Phần mềm kiểm kê mới này hiệu quả hơn đáng kể so với phiên bản doanh nghiệp trước đó.",
        difficulty: "500-750",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: false,
  },
  {
    id: "g-modal-subjunctive",
    code: "MV-12",
    title: "Động Từ Khuyết Thiếu & Thể Giả Định",
    englishTitle: "Modal Verbs & Subjunctive Mood",
    part: "Part 5",
    targetScore: "750+",
    status: "PUBLISHED",
    summary: "Cấu trúc câu giả định với các động từ yêu cầu, đề xuất (require, recommend, suggest, insist) thì mệnh đề 'that' luôn dùng V nguyên mẫu không 'to'.",
    formula: "S + recommend/request/require + THAT + S + (should) + V_inf",
    signalWords: ["recommend that", "require that", "it is imperative that", "it is essential that", "must", "should"],
    traps: [
      "Bẫy giả định: Cho dù chủ ngữ sau THAT là ngôi thứ ba số ít (he/she/it/the manager), động từ theo sau VẪN Ở DẠNG NGUYÊN THỂ (vì đã ẩn từ 'should').",
    ],
    examples: [
      {
        sentence: "The auditor recommended that the director submit the expenditure records by Friday.",
        translation: "Kiểm toán viên đã khuyến nghị giám đốc nộp các bản ghi chi tiêu trước thứ Sáu.",
        analysis: "Subjunctive mood: submit ở dạng nguyên thể dù chủ ngữ 'the director' số ít.",
      },
    ],
    questions: [
      {
        id: "mv-q1",
        part: "Part 5",
        questionText: "The external auditor recommended that the finance director _______ the revised balance sheet immediately.",
        options: {
          A: "submit",
          B: "submits",
          C: "submitted",
          D: "submitting",
        },
        correctAnswer: "A",
        explanation: "Cấu trúc giả định thức: Sau động từ 'recommended that + S', động từ theo sau luôn ở dạng NGUYÊN MẪU KHÔNG CHIA (submit), bất kể thì của câu hay chủ ngữ số ít 'the finance director'.",
        trapNote: "Bẫy siêu khó Part 5: Thí sinh thấy 'the finance director' số ít nên chọn 'submits' (B) hoặc thấy 'recommended' quá khứ nên chọn 'submitted' (C). Cả hai đều sai!",
        translation: "Kiểm toán viên độc lập đã khuyến nghị giám đốc tài chính nộp bảng cân đối kế toán sửa đổi ngay lập tức.",
        difficulty: "750+",
      },
    ],
    studiedCount: 0,
    correctCount: 0,
    wrongCount: 0,
    bookmarked: true,
  },
];
