name: ai_toeic_learning_system

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: toeic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: toeic_ai_learning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TuanDat0608
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    image: ai_toeic_learning_system-backend:latest
    container_name: toeic-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/toeic_ai_learning
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: TuanDat0608
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001}"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    image: ai_toeic_learning_system-frontend:latest
    container_name: toeic-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
    external: true
    name: toeic_ai_learning_pgdata