import { TestItem, PracticeQuestion } from "./types";

export const SAMPLE_EXAM_QUESTIONS: PracticeQuestion[] = [
  // ================= LISTENING SECTION (PART 1 - 4) =================
  // --- PART 1: PHOTOGRAPHS (6 câu) ---
  {
    id: 1,
    part: "Part 1",
    questionText: "Look at the photograph and choose the statement that best describes what you see.",
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    options: {
      A: "A chef is preparing food in a commercial kitchen.",
      B: "Plates are being washed in a sink.",
      C: "Food is being served to restaurant customers.",
      D: "Groceries are being loaded into a delivery truck.",
    },
    correctAnswer: "A",
    transcript: "(A) A chef is preparing food in a commercial kitchen. (B) Plates are being washed in a sink. (C) Food is being served to restaurant customers. (D) Groceries are being loaded into a delivery truck.",
    translation: "(A) Một đầu bếp đang chuẩn bị đồ ăn trong bếp thương mại. (B) Bát đĩa đang được rửa trong bồn. (C) Thức ăn đang được phục vụ cho khách hàng. (D) Hàng hóa đang được chất lên xe giao hàng.",
    explanation: "Bức ảnh thể hiện người đầu bếp đang đứng nấu ăn bên bếp lò trong nhà bếp nhà hàng -> Phương án (A) mô tả đúng nhất.",
  },
  {
    id: 2,
    part: "Part 1",
    questionText: "Look at the photograph and choose the best description.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    options: {
      A: "Some people are seated around a conference table.",
      B: "Documents are being filed in the cabinet.",
      C: "A presentation is being displayed on the monitor.",
      D: "The office windows are currently being cleaned.",
    },
    correctAnswer: "A",
    transcript: "(A) Some people are seated around a conference table.",
    translation: "(A) Một số người đang ngồi quanh bàn họp.",
    explanation: "Nhân sự đang ngồi trao đổi xung quanh bàn họp lớn.",
  },

  // --- PART 2: QUESTION - RESPONSE (25 câu - chỉ có A, B, C) ---
  {
    id: 7,
    part: "Part 2",
    questionText: "When is the annual budget proposal scheduled to be submitted?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    options: {
      A: "Yes, our team approved it yesterday.",
      B: "By the end of business hours this Friday.",
      C: "In the main boardroom on the fifth floor.",
    },
    correctAnswer: "B",
    transcript: "Question: When is the annual budget proposal scheduled to be submitted? (A) Yes, approved yesterday. (B) By Friday. (C) On the fifth floor.",
    translation: "Câu hỏi: Khi nào đề xuất ngân sách hàng năm dự kiến được nộp? (A) Vâng, đã duyệt. (B) Trước thứ Sáu này. (C) Ở tầng 5.",
    explanation: "Câu hỏi 'When' hỏi về thời gian -> (B) đưa ra thời hạn cụ thể.",
  },
  {
    id: 8,
    part: "Part 2",
    questionText: "Why hasn't the overseas shipment from Tokyo arrived yet?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    options: {
      A: "Severe weather conditions delayed international flights.",
      B: "No, we only received forty cartons.",
      C: "Mr. Sato is the chief logistics coordinator.",
    },
    correctAnswer: "A",
    translation: "Tại sao lô hàng từ Tokyo chưa tới?",
    explanation: "Câu hỏi 'Why' hỏi nguyên nhân -> (A) giải thích do thời tiết xấu hoãn chuyến bay.",
  },

  // --- PART 3: SHORT CONVERSATIONS ---
  {
    id: 32,
    part: "Part 3",
    groupTitle: "Questions 32–34 refer to the following conversation.",
    groupId: "32–34",
    groupTotal: 3,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    questionText: "32. Where does the conversation most likely take place?",
    options: {
      A: "At an electronics retail store",
      B: "In a corporate medical clinic",
      C: "At an airport check-in counter",
      D: "In a hotel reception lobby",
    },
    optionGlosses: {
      A: "Cửa hàng bán lẻ đồ điện tử",
      B: "Phòng khám y tế doanh nghiệp",
      C: "Quầy làm thủ tục sân bay",
      D: "Sảnh lễ tân khách sạn",
    },
    correctAnswer: "D",
    translation: "Cuộc trò chuyện có khả năng diễn ra ở đâu nhất?",
    explanation: "Người đàn ông hỏi về reservation phòng và chìa khóa phòng -> sảnh lễ tân khách sạn.",
  },
  {
    id: 33,
    part: "Part 3",
    groupTitle: "Questions 32–34 refer to the following conversation.",
    groupId: "32–34",
    groupTotal: 3,
    questionText: "33. What problem does the woman mention?",
    options: {
      A: "The executive suite is not cleaned yet.",
      B: "A credit card payment was declined.",
      C: "The shuttle bus service has been cancelled.",
      D: "The air conditioning unit is broken.",
    },
    correctAnswer: "A",
    translation: "Người phụ nữ nhắc tới sự cố gì?",
    explanation: "Nhân viên báo phòng suite chưa dọn dẹp xong.",
  },

  // --- PART 4: SHORT TALKS ---
  {
    id: 71,
    part: "Part 4",
    groupTitle: "Questions 71–73 refer to the following announcement.",
    groupId: "71–73",
    groupTotal: 3,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    questionText: "71. Who is the speaker most likely addressing?",
    options: {
      A: "Factory assembly line workers",
      B: "New corporate employees at orientation",
      C: "Passengers on a guided tour bus",
      D: "Store managers at a sales conference",
    },
    correctAnswer: "B",
    translation: "Người nói đang hướng tới đối tượng nào?",
    explanation: "Thông báo chào mừng nhân viên mới trong ngày định hướng công ty.",
  },

  // ================= READING SECTION (PART 5 - 7) =================
  // --- PART 5: INCOMPLETE SENTENCES ---
  {
    id: 101,
    part: "Part 5",
    questionText: "The board must be given written notice of -------- to the retirement plan at least 30 days in advance.",
    options: {
      A: "revisions",
      B: "revising",
      C: "revised",
      D: "revises",
    },
    optionGlosses: {
      A: "(n-plural): những sự sửa đổi",
      B: "(v-ing): đang sửa đổi",
      C: "(v-ed): đã sửa đổi",
      D: "(v-s): sửa đổi",
    },
    correctAnswer: "A",
    translation: "Hội đồng quản trị phải được thông báo bằng văn bản về những sửa đổi đối với chương trình hưu trí ít nhất 30 ngày trước.",
    step1: 'Bốn đáp án là các dạng khác nhau của đại từ "revisions" nên cần xét vị trí chỗ trống.',
    step2: 'Sau giới từ "of" cần danh từ đóng vai trò tân ngữ -> loại động từ revising/revised/revises.',
    step3: 'Chọn danh từ số nhiều "revisions" (những sự sửa đổi).',
    explanation: "Sau giới từ 'of' cần danh từ số nhiều 'revisions'.",
  },
  {
    id: 102,
    part: "Part 5",
    questionText: "Upon the two founders' retirement, the foundation released a booklet describing ------- earliest projects.",
    options: {
      A: "they",
      B: "them",
      C: "their",
      D: "themselves",
    },
    optionGlosses: {
      A: "(pron): họ",
      B: "(pron): họ (tân ngữ)",
      C: "(adj sở hữu): của họ",
      D: "(pron): chính họ",
    },
    correctAnswer: "C",
    translation: "Nhân dịp hai nhà sáng lập nghỉ hưu, quỹ đã phát hành một cuốn sách nhỏ mô tả những dự án đầu tiên của họ.",
    step1: 'Bốn đáp án là các dạng khác nhau của đại từ "they" nên đây là câu đại từ, cần xét vị trí chỗ trống.',
    step2: 'Chỗ trống đứng ngay trước cụm danh từ "earliest projects", cần tính từ sở hữu.',
    step3: 'Chọn tính từ sở hữu "their" (của họ).',
    explanation: "Đứng trước cụm danh từ 'earliest projects' cần tính từ sở hữu 'their'.",
  },

  // --- PART 6: TEXT COMPLETION ---
  {
    id: 131,
    part: "Part 6",
    groupTitle: "Questions 131–134 refer to the following article.",
    groupId: "131–134",
    groupTotal: 4,
    passage: `(March 8)—Clothing rental services, which let customers borrow outfits for a monthly fee instead of buying them, are currently enjoying a boom nationwide. The number of subscribers grew nearly 40% in the past year, and rental racks can now be found in a ------- (131) range of stores, from small boutiques to national department chains.

A major reason for this trend is changing shopper ------- (132) shaped by concern about the waste created by fast fashion. According to Marina Delgado, spokesperson for the Garment Rental Council, the lower monthly fees and larger selection of newer services have helped ------- (133). Ms. Delgado believes that this part of the industry will only continue to grow. ------- (134)`,
    questionText: "131.",
    options: {
      A: "distant",
      B: "wide",
      C: "frequent",
      D: "various",
    },
    optionGlosses: {
      A: "(adj): xa xôi",
      B: "(adj): rộng rãi, đa dạng",
      C: "(adj): thường xuyên",
      D: "(adj): khác nhau",
    },
    correctAnswer: "B",
    translation: "Một phạm vi cửa hàng rộng lớn...",
    explanation: "Cụm từ cố định 'a wide range of' (một phạm vi rộng/đa dạng).",
  },

  // --- PART 7: READING COMPREHENSION ---
  {
    id: 147,
    part: "Part 7",
    groupTitle: "Questions 147–148 refer to the following notice.",
    groupId: "147–148",
    groupTotal: 2,
    passage: `MEADOWLARK GARDEN CENTRES – HEAD OFFICE

STAFF TRAINING SESSION

Topic: Choosing Stock for the Spring Season
Presenter: Dana Okonkwo, Okonkwo Nursery Group
Date: 14 March, 2:00 P.M.
Location: www.link-room.co.uk (Session Code: 447 210 665)

Attendance is required for anyone who places orders with our growers. The session runs for ninety minutes and will not be recorded. Please e-mail any questions you would like Ms. Okonkwo to answer to training@meadowlark.co.uk by 10 March.`,
    evidence: "Attendance is required for anyone who places orders with our growers.",
    questionText: "147. Who will most likely attend the session?",
    options: {
      A: "Delivery drivers",
      B: "Shop-floor assistants",
      C: "Growers from local nurseries",
      D: "Employees who buy stock",
    },
    optionGlosses: {
      A: "Tài xế giao hàng",
      B: "Trợ lý bán hàng tại quầy",
      C: "Người trồng cây tại nhà vườn địa phương",
      D: "Nhân viên mua hàng hóa",
    },
    correctAnswer: "D",
    translation: "Ai là người có khả năng nhất sẽ tham gia buổi đào tạo?",
    explanation: "Việc tham gia là bắt buộc cho bất kỳ ai đặt hàng với các nhà vườn -> Nhân viên mua hàng hóa.",
  },
  {
    id: 148,
    part: "Part 7",
    groupTitle: "Questions 147–148 refer to the following notice.",
    groupId: "147–148",
    groupTotal: 2,
    questionText: "148. What are employees asked to do before 10 March?",
    options: {
      A: "Send in questions for the presenter",
      B: "Confirm their attendance with a manager",
      C: "Register on the company website",
      D: "Download the training booklet",
    },
    optionGlosses: {
      A: "Gửi câu hỏi cho diễn giả",
      B: "Xác nhận sự tham gia với quản lý",
      C: "Đăng ký trên website công ty",
      D: "Tải xuống tài liệu đào tạo",
    },
    correctAnswer: "A",
    translation: "Nhân viên được yêu cầu làm gì trước ngày 10 tháng 3?",
    evidence: "Please e-mail any questions you would like Ms. Okonkwo to answer to training@meadowlark.co.uk by 10 March.",
    explanation: "Thông báo yêu cầu gửi email các câu hỏi cho diễn giả trước 10/3.",
  },
];

export const INITIAL_TESTS_VOL1: TestItem[] = [
  {
    id: 1,
    volId: "vol1",
    title: "Test 1",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "reimbursement", ipa: "/ˌriːɪmˈbɜːrsmənt/", pos: "n", meaning: "Khoản hoàn tiền công tác, bồi hoàn chi phí", example: "Submit receipts to claim meal reimbursement." },
      { word: "complimentary", ipa: "/ˌkɑːmplɪˈmentri/", pos: "adj", meaning: "Miễn phí, tặng kèm", example: "Guests receive complimentary shuttle transportation." },
      { word: "delegate", ipa: "/ˈdelɪɡət/", pos: "n/v", meaning: "Đại biểu, người đại diện / Ủy quyền giao việc", example: "The conference welcomed over 300 international delegates." },
      { word: "itinerary", ipa: "/aɪˈtɪnəreri/", pos: "n", meaning: "Lịch trình chi tiết chuyến đi", example: "Check your flight itinerary prior to departure." },
      { word: "substantial", ipa: "/səbˈstænʃl/", pos: "adj", meaning: "Đáng kể, to lớn", example: "The firm saw a substantial increase in quarterly profit." },
    ],
  },
  {
    id: 2,
    volId: "vol1",
    title: "Test 2",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "feasibility", ipa: "/ˌfiːzəˈbɪləti/", pos: "n", meaning: "Tính khả thi của dự án", example: "Engineers conducted a feasibility study on solar power." },
      { word: "mandatory", ipa: "/ˈmændətɔːri/", pos: "adj", meaning: "Bắt buộc, theo quy định", example: "Attendance at the safety orientation is mandatory." },
      { word: "preliminary", ipa: "/prɪˈlɪmɪneri/", pos: "adj", meaning: "Sơ bộ, ban đầu", example: "Preliminary findings show strong market demand." },
      { word: "fluctuate", ipa: "/ˈflʌktʃueɪt/", pos: "v", meaning: "Dao động, biến động thất thường", example: "Currency exchange rates fluctuate constantly." },
    ],
  },
  {
    id: 3,
    volId: "vol1",
    title: "Test 3",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "consensus", ipa: "/kənˈsensəs/", pos: "n", meaning: "Sự đồng thuận chung của tập thể", example: "The committee reached a consensus on the budget." },
      { word: "prospective", ipa: "/prəˈspektɪv/", pos: "adj", meaning: "Tiềm năng, có triển vọng tương lai", example: "We sent catalogs to prospective corporate buyers." },
      { word: "expedite", ipa: "/ˈekspədaɪt/", pos: "v", meaning: "Xúc tiến nhanh, đẩy nhanh tiến độ", example: "Please pay an express fee to expedite shipping." },
    ],
  },
  {
    id: 4,
    volId: "vol1",
    title: "Test 4",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "accommodate", ipa: "/əˈkɑːmədeɪt/", pos: "v", meaning: "Đáp ứng nhu cầu, chứa đủ người", example: "The banquet hall accommodates up to 500 guests." },
      { word: "stipulation", ipa: "/ˌstɪpjuˈleɪʃn/", pos: "n", meaning: "Điều khoản bắt buộc trong hợp đồng", example: "The contract contains a strict warranty stipulation." },
    ],
  },
  {
    id: 5,
    volId: "vol1",
    title: "Test 5",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "adjacent", ipa: "/əˈdʒeɪsnt/", pos: "adj", meaning: "Kế bên, liền kề sát cạnh", example: "The parking lot is adjacent to Terminal 2." },
      { word: "lucrative", ipa: "/ˈluːkrətɪv/", pos: "adj", meaning: "Sinh lời lớn, béo bở", example: "Securing the government contract proved lucrative." },
    ],
  },
  {
    id: 6,
    volId: "vol1",
    title: "Test 6",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "discrepancy", ipa: "/dɪˈskrepənsi/", pos: "n", meaning: "Sự sai lệch, không khớp số liệu", example: "Auditors noted a discrepancy in travel invoices." },
      { word: "facilitate", ipa: "/fəˈsɪlɪteɪt/", pos: "v", meaning: "Tạo điều kiện thuận lợi, hỗ trợ", example: "Modern tools facilitate seamless communication." },
    ],
  },
  {
    id: 7,
    volId: "vol1",
    title: "Test 7",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "contingency", ipa: "/kənˈtɪndʒənsi/", pos: "n", meaning: "Phương án dự phòng rủi ro", example: "Establish a contingency plan in case of shipment delays." },
      { word: "rigorous", ipa: "/ˈrɪɡərəs/", pos: "adj", meaning: "Nghiêm ngặt, khắt khe", example: "The candidate passed rigorous technical evaluations." },
    ],
  },
  {
    id: 8,
    volId: "vol1",
    title: "Test 8",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "tenative", ipa: "/ˈtentətɪv/", pos: "adj", meaning: "Dự kiến, tạm thời chưa chốt", example: "We set a tentative project launch date for May 15." },
      { word: "unprecedented", ipa: "/ʌnˈpresɪdentɪd/", pos: "adj", meaning: "Chưa từng có tiền lệ", example: "The product release enjoyed unprecedented demand." },
    ],
  },
  {
    id: 9,
    volId: "vol1",
    title: "Test 9",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "apparel", ipa: "/əˈpærəl/", pos: "n", meaning: "Trang phục, quần áo thương mại", example: "The boutique imports designer apparel from Milan." },
      { word: "endorse", ipa: "/ɪnˈdɔːrs/", pos: "v", meaning: "Tán thành, ủng hộ, quảng bá", example: "Celebrity athletes officially endorse the sportswear line." },
    ],
  },
  {
    id: 10,
    volId: "vol1",
    title: "Test 10",
    difficulty: "Khó",
    score: null,
    listeningScore: null,
    readingScore: null,
    status: "Chưa luyện tập",
    completedAt: null,
    historyAttempts: [],
    keyVocab: [
      { word: "lucrative", ipa: "/ˈluːkrətɪv/", pos: "adj", meaning: "Sinh lợi cao, mang lại nhiều tiền", example: "A lucrative sponsorship contract was signed." },
      { word: "reputable", ipa: "/ˈrepjətəbl/", pos: "adj", meaning: "Có uy tín lớn, đáng tin cậy", example: "Always source spare parts from reputable suppliers." },
    ],
  },
];

export const INITIAL_TESTS_VOL2: TestItem[] = Array.from({ length: 10 }, (_, i) => ({
  id: i + 1,
  volId: "vol2",
  title: `Test ${i + 1}`,
  difficulty: "Khó",
  score: null,
  listeningScore: null,
  readingScore: null,
  status: "Chưa luyện tập",
  completedAt: null,
  historyAttempts: [],
  keyVocab: [
    { word: "solicit", ipa: "/səˈlɪsɪt/", pos: "v", meaning: "Kêu gọi, khẩn khoản xin ý kiến đóng góp", example: "We solicit feedback from all attendees." },
    { word: "subsidiary", ipa: "/səbˈsɪdieri/", pos: "n", meaning: "Công ty con trực thuộc tập đoàn", example: "The Tokyo branch is our newest subsidiary." },
  ],
}));
