import { DictationQuestion, DictationCardData, LevelCategoryCardData } from "./types";

export const SAMPLE_DICTATION_QUESTIONS: DictationQuestion[] = [
  // Part 1
  {
    id: 1,
    part: "Part 1",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186156f?auto=format&fit=crop&w=800&q=80",
    fullTranscript: "He's climbing a ladder.",
    vietnameseTranslation: "Anh ấy đang leo lên một chiếc thang.",
    options: {
      A: "He's standing on a rug.",
      B: "He's turning a doorknob.",
      C: "He's climbing a ladder.",
      D: "He's painting a wall.",
    },
    optionTranslations: {
      A: "Anh ấy đang đứng trên một tấm thảm.",
      B: "Anh ấy đang vặn nắm cửa.",
      C: "Anh ấy đang leo lên một chiếc thang.",
      D: "Anh ấy đang sơn một bức tường.",
    },
    correctAnswer: "C",
    explanation: "Động từ 'is climbing a ladder' mô tả chính xác người đàn ông đang bước leo lên chiếc thang trong hình.",
    trapNote: "Chú ý quan sát bức tranh: Người đàn ông đang ở trên nấc thang chứ không đứng dưới thảm hay sơn tường.",
    vocabList: [
      { word: "rug", pos: "n", level: "B2", ipa: "/rʌɡ/", meaning: "tấm thảm" },
      { word: "doorknob", pos: "n", level: "C1", ipa: "/ˈdɔːrnɑːb/", meaning: "nắm cửa" },
      { word: "climb", pos: "v", level: "B1", ipa: "/klaɪm/", meaning: "leo" },
      { word: "ladder", pos: "n", level: "B1", ipa: "/ˈlædər/", meaning: "cái thang" },
    ],
  },
  {
    id: 2,
    part: "Part 1",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
    fullTranscript: "Cardboard boxes are stacked neatly in the distribution warehouse.",
    vietnameseTranslation: "Các thùng bìa các-tông được xếp chồng gọn gàng trong kho phân phối.",
    options: {
      A: "A forklift is unloading cargo from the ship.",
      B: "Cardboard boxes are stacked neatly in the warehouse.",
      C: "Workers are inspecting conveyor machinery.",
      D: "A delivery van is parked beside the platform.",
    },
    correctAnswer: "B",
    explanation: "Hình ảnh tập trung vào các thùng hàng carton được xếp ngay ngắn thành nhiều tầng trong kho bãi.",
    trapNote: "Bẫy danh từ liên quan: Nhắc đến 'warehouse' dễ nghĩ đến 'forklift' (xe nâng) nhưng trong tranh không có xe nâng.",
  },
  // Part 2
  {
    id: 3,
    part: "Part 2",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    fullTranscript: "When is the quarterly financial audit report due for submission?",
    vietnameseTranslation: "Khi nào bản báo cáo kiểm toán tài chính hàng quý đến hạn phải nộp?",
    options: {
      A: "Yes, our team audited it yesterday.",
      B: "By five o'clock this Friday afternoon.",
      C: "In the conference hall on the fifth floor.",
    },
    correctAnswer: "B",
    explanation: "Câu hỏi bắt đầu bằng 'When' (Khi nào) hỏi thời hạn -> 'By five o'clock this Friday afternoon' là câu trả lời trực tiếp.",
    trapNote: "Bẫy Yes/No: Câu hỏi có từ để hỏi Wh- không bao giờ trả lời bằng Yes hoặc No (loại A ngay lập tức).",
  },
  {
    id: 4,
    part: "Part 2",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    fullTranscript: "Why was the regional sales conference postponed until next month?",
    vietnameseTranslation: "Tại sao hội nghị bán hàng khu vực lại bị hoãn đến tháng sau?",
    options: {
      A: "Severe storm warnings disrupted regional airline schedules.",
      B: "No, we already booked eighty hotel rooms.",
      C: "Mr. Campbell is the keynote speaker.",
    },
    correctAnswer: "A",
    explanation: "Câu hỏi 'Why' hỏi lý do -> (A) giải thích do cảnh báo bão lớn làm gián đoạn lịch trình các chuyến bay.",
    trapNote: "Bẫy từ cùng chủ đề: Nhắc đến conference đưa ra keynote speaker để gây nhầm lẫn nội dung.",
  },
  // Part 3 - Set 83-85
  {
    id: 5,
    part: "Part 3",
    question: "What type of business does the speaker own?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    fullTranscript: "Welcome to Pottery Studio. Today we will demonstrate crafting ceramic bowls.",
    vietnameseTranslation: "Chào mừng đến với xưởng xốm Pottery Studio.",
    options: {
      A: "A tea shop",
      B: "A childcare center",
      C: "A pottery studio",
      D: "A party supply store",
    },
    optionTranslations: {
      A: "Một quán trà",
      B: "Một trung tâm chăm sóc trẻ em",
      C: "Một xưởng làm đồ gốm",
      D: "Một cửa hàng tiệc tùng",
    },
    correctAnswer: "C",
    explanation: "Bài nói bắt đầu bằng việc chào mừng tới 'Pottery Studio'.",
    vocabList: [
      { word: "pottery", pos: "n", level: "B2", ipa: "/ˈpɑːtəri/", meaning: "nghề làm gốm, xưởng gốm" },
      { word: "demonstrate", pos: "v", level: "B2", ipa: "/ˈdemənstreɪt/", meaning: "trình diễn, hướng dẫn" },
    ],
  },
  {
    id: 6,
    part: "Part 3",
    question: "What does the speaker imply when she says, \"you've worked here for five months now\"?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    fullTranscript: "You've worked here for five months now, so you should be familiar with this.",
    vietnameseTranslation: "Bạn đã làm việc ở đây 5 tháng rồi, nên bạn đã đủ khả năng thực hiện.",
    options: {
      A: "The listener is capable of doing a task.",
      B: "The listener should apply for a promotion.",
      C: "The listener is taking too long to complete a project.",
      D: "The listener qualifies for a salary raise.",
    },
    optionTranslations: {
      A: "Người nghe đủ khả năng thực hiện công việc.",
      B: "Người nghe nên nộp đơn xin thăng chức.",
      C: "Người nghe tốn quá nhiều thời gian hoàn thành dự án.",
      D: "Người nghe đủ điều kiện tăng lương.",
    },
    correctAnswer: "A",
    explanation: "Câu nói ngụ ý người nghe đã làm 5 tháng nên hoàn toàn đủ khả năng tự hoàn thành nhiệm vụ.",
  },
  {
    id: 7,
    part: "Part 3",
    question: "What will the speakers do next?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    fullTranscript: "Now let's head over to the kiln room to inspect the fired clay products.",
    vietnameseTranslation: "Bây giờ chúng ta hãy cùng sang phòng lò nung để hướng dẫn kỹ thuật.",
    options: {
      A: "Inspect an oven",
      B: "Review a contract",
      C: "Clean a storage room",
      D: "Demonstrate a technique",
    },
    optionTranslations: {
      A: "Kiểm tra lò nung",
      B: "Xem xét hợp đồng",
      C: "Dọn dẹp phòng kho",
      D: "Trình diễn một kỹ thuật mới",
    },
    correctAnswer: "D",
    explanation: "Người nói mời tiếp tục theo dõi buổi thực hành trình diễn kỹ thuật.",
  },
  // Part 4 - Set 95-97
  {
    id: 8,
    part: "Part 4",
    question: "What is the main purpose of the announcement?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    fullTranscript: "Attention all staff, routine elevator maintenance is scheduled for this Friday.",
    vietnameseTranslation: "Xin chú ý, lịch bảo trì thang máy định kỳ sẽ diễn ra vào thứ Sáu.",
    options: {
      A: "To report a schedule delay",
      B: "To introduce a new department head",
      C: "To announce a facility maintenance schedule",
      D: "To invite staff to a company picnic",
    },
    optionTranslations: {
      A: "Báo cáo việc chậm lịch trình",
      B: "Giới thiệu trưởng bộ phận mới",
      C: "Thông báo lịch bảo trì cơ sở vật chất",
      D: "Mời nhân viên tham gia dã ngoại công ty",
    },
    correctAnswer: "C",
    explanation: "Thông báo về việc bảo trì thang máy tòa nhà.",
  },
  {
    id: 9,
    part: "Part 4",
    question: "According to the speaker, what should employees do before Friday?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    fullTranscript: "Please archive all client files properly before Friday noon.",
    vietnameseTranslation: "Vui lòng lưu trữ các tệp hồ sơ khách hàng trước trưa thứ Sáu.",
    options: {
      A: "Submit time sheets",
      B: "Archive client files",
      C: "Confirm hotel reservations",
      D: "Update passwords",
    },
    optionTranslations: {
      A: "Nộp bảng chấm công",
      B: "Lưu trữ tệp hồ sơ khách hàng",
      C: "Xác định đặt phòng khách sạn",
      D: "Cập nhật mật khẩu",
    },
    correctAnswer: "B",
    explanation: "Yêu cầu nhân viên lưu trữ hồ sơ client files.",
  },
  {
    id: 10,
    part: "Part 4",
    question: "What will happen at 5:00 PM?",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    fullTranscript: "The main elevators will be shut down at 5:00 PM.",
    vietnameseTranslation: "Thang máy chính sẽ ngừng hoạt động lúc 5:00 chiều.",
    options: {
      A: "The elevators will be shut down",
      B: "The main lobby will be closed",
      C: "A staff meeting will commence",
      D: "A system backup will run",
    },
    optionTranslations: {
      A: "Thang máy sẽ ngừng hoạt động",
      B: "Sảnh chính sẽ bị đóng cửa",
      C: "Cuộc họp nhân viên sẽ bắt đầu",
      D: "Hệ thống sẽ chạy sao lưu",
    },
    correctAnswer: "A",
    explanation: "Thang máy chính ngắt điện bảo trì từ 5:00 chiều.",
  },
];

export const INITIAL_DICTATION_CARDS: DictationCardData[] = [
  // Test 1
  {
    id: "t1-p1",
    testNumber: 1,
    part: "Part 1",
    year: "2026",
    totalQuestions: 24,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [
      { word: "boardroom", ipa: "/ˈbɔːrdruːm/", meaning: "Phòng họp ban giám đốc", example: "The executives gathered in the boardroom." },
      { word: "stacked", ipa: "/stækt/", meaning: "Được xếp chồng lên nhau", example: "Boxes were stacked neatly." },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[0], SAMPLE_DICTATION_QUESTIONS[1]],
  },
  {
    id: "t1-p2",
    testNumber: 1,
    part: "Part 2",
    year: "2026",
    totalQuestions: 100,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [
      { word: "audit", ipa: "/ˈɔːdɪt/", meaning: "Kiểm toán tài chính", example: "An annual audit is required." },
      { word: "postpone", ipa: "/poʊˈspoʊn/", meaning: "Hoãn lại lịch trình", example: "The summit was postponed." },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[2], SAMPLE_DICTATION_QUESTIONS[3]],
  },
  {
    id: "t1-p3",
    testNumber: 1,
    part: "Part 3",
    year: "2026",
    totalQuestions: 111,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [
      { word: "expedited", ipa: "/ˈekspədaɪtɪd/", meaning: "Hỏa tốc, xúc tiến nhanh", example: "We paid for expedited freight." },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "t1-p4",
    testNumber: 1,
    part: "Part 4",
    year: "2026",
    totalQuestions: 75,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [
      { word: "relocate", ipa: "/ˌriːˈloʊkeɪt/", meaning: "Chuyển địa điểm, dời chỗ", example: "The boarding gate was relocated." },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  // Test 2
  {
    id: "t2-p1",
    testNumber: 2,
    part: "Part 1",
    year: "2026",
    totalQuestions: 24,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[0], SAMPLE_DICTATION_QUESTIONS[1]],
  },
  {
    id: "t2-p2",
    testNumber: 2,
    part: "Part 2",
    year: "2026",
    totalQuestions: 100,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[2], SAMPLE_DICTATION_QUESTIONS[3]],
  },
  {
    id: "t2-p3",
    testNumber: 2,
    part: "Part 3",
    year: "2026",
    totalQuestions: 132,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "t2-p4",
    testNumber: 2,
    part: "Part 4",
    year: "2026",
    totalQuestions: 79,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  // Test 3
  {
    id: "t3-p1",
    testNumber: 3,
    part: "Part 1",
    year: "2026",
    totalQuestions: 24,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[0], SAMPLE_DICTATION_QUESTIONS[1]],
  },
  {
    id: "t3-p2",
    testNumber: 3,
    part: "Part 2",
    year: "2026",
    totalQuestions: 100,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[2], SAMPLE_DICTATION_QUESTIONS[3]],
  },
  {
    id: "t3-p3",
    testNumber: 3,
    part: "Part 3",
    year: "2026",
    totalQuestions: 120,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "t3-p4",
    testNumber: 3,
    part: "Part 4",
    year: "2026",
    totalQuestions: 82,
    completedQuestions: 0,
    status: "Chưa bắt đầu",
    notesCount: 0,
    vocabItems: [],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
];

export const INITIAL_PART1_LEVELS: LevelCategoryCardData[] = [
  {
    id: "p1-l1",
    part: "Part 1",
    type: "level",
    title: "Lv.1 Dưới 200",
    targetLevel: "Dưới 200",
    totalQuestions: 27,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Tập trung các động tác rõ ràng của 1 người: ngồi, đứng, cầm nắm đồ vật, nhìn vào tài liệu.",
    rules: [
      "Nghe rõ động từ chỉ hành động cơ bản: holding, looking at, typing, carrying, sitting.",
      "Quan sát danh từ chỉ đồ vật gần người nhất.",
    ],
    vocabBag: [
      { word: "holding", ipa: "/ˈhoʊldɪŋ/", meaning: "Đang cầm, nắm vật thể" },
      { word: "gazing", ipa: "/ˈɡeɪzɪŋ/", meaning: "Nhìn chăm chú vào" },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[0]],
  },
  {
    id: "p1-l2",
    part: "Part 1",
    type: "level",
    title: "Lv.2 200–500",
    targetLevel: "200–300",
    totalQuestions: 65,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Các bức tranh có 2 người trở lên, miêu tả hành động tương tác hoặc cùng nhìn về một hướng.",
    rules: [
      "Phân biệt hành động của từng người (one person vs both people).",
      "Chú ý các động từ giao tiếp: talking, listening, discussing, handing.",
    ],
    vocabBag: [
      { word: "handing", ipa: "/ˈhændɪŋ/", meaning: "Đưa vật gì đó cho người khác" },
      { word: "assembling", ipa: "/əˈsemblɪŋ/", meaning: "Tập hợp lại cùng nhau" },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[0]],
  },
  {
    id: "p1-l3",
    part: "Part 1",
    type: "level",
    title: "Lv.3 500–750",
    targetLevel: "300–400",
    totalQuestions: 60,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Tranh miêu tả đồ vật và cảnh quan tĩnh, thường dùng cấu trúc bị động chỉ trạng thái (have been arranged).",
    rules: [
      "Bẫy thì hiện tại tiếp diễn bị động 'being + V3' (chỉ có người đang thao tác mới được chọn).",
      "Dùng cấu trúc trạng thái: 'have been placed', 'are lined up', 'scattered'.",
    ],
    vocabBag: [
      { word: "arranged", ipa: "/əˈreɪndʒd/", meaning: "Được sắp đặt ngăn nắp" },
      { word: "displayed", ipa: "/dɪˈspleɪd/", meaning: "Được trưng bày trên kệ" },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[1]],
  },
  {
    id: "p1-l4",
    part: "Part 1",
    type: "level",
    title: "Lv.4 750–990",
    targetLevel: "400–495",
    totalQuestions: 23,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Tranh trừu tượng, từ vựng khó chỉ góc nhìn cảnh vật thiên nhiên hoặc chi tiết máy móc phức tạp.",
    rules: [
      "Bẫy từ vựng lạ: awning, pier, pedestrian crossing, partition, wheelbarrow.",
      "Mô tả vị trí tương đối: overlooking, stretching, flanking.",
    ],
    vocabBag: [
      { word: "overlooking", ipa: "/ˌoʊvərˈlʊkɪŋ/", meaning: "Nhìn ra hướng (sông, bờ biển)" },
      { word: "sheltered", ipa: "/ˈʃeltərd/", meaning: "Được che chắn khỏi mưa nắng" },
    ],
    questions: [SAMPLE_DICTATION_QUESTIONS[1]],
  },
];

export const INITIAL_PART1_CATEGORIES: LevelCategoryCardData[] = [
  {
    id: "p1-c1",
    part: "Part 1",
    type: "category",
    title: "Tranh một người",
    totalQuestions: 66,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Tập trung tuyệt đối vào người trong ảnh: tay đang làm gì, mắt nhìn đâu, trang phục đang mặc (wearing vs putting on).",
    rules: ["Phân biệt 'wearing' (đang mặc trên người) và 'putting on' (đang xỏ tay vào mặc)."],
    vocabBag: [{ word: "adjusting", ipa: "/əˈdʒʌstɪŋ/", meaning: "Đang chỉnh kính/đồng hồ" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[0]],
  },
  {
    id: "p1-c2",
    part: "Part 1",
    type: "category",
    title: "Tranh nhiều người",
    totalQuestions: 33,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Tìm điểm chung của đám đông hoặc sự khác biệt nổi bật của 1 nhân vật trong nhóm.",
    rules: ["Nhận diện các đại từ: 'Some people', 'All of them', 'One of the men'."],
    vocabBag: [{ word: "gathering", ipa: "/ˈɡæðərɪŋ/", meaning: "Đang tụ họp lại" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[0]],
  },
  {
    id: "p1-c3",
    part: "Part 1",
    type: "category",
    title: "Tranh tả cảnh",
    totalQuestions: 14,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Không có người hoặc người rất nhỏ ở phía xa, tập trung vào đường phố, công viên, bến cảng.",
    rules: ["Loại ngay các đáp án có người làm chủ ngữ hoặc có chữ 'being'."],
    vocabBag: [{ word: "paved", ipa: "/peɪvd/", meaning: "Được lát gạch / trải nhựa" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[1]],
  },
  {
    id: "p1-c4",
    part: "Part 1",
    type: "category",
    title: "Tranh tả vật",
    totalQuestions: 62,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Đồ đạc nội thất, kệ hàng siêu thị, giá sách, phương tiện giao thông xếp hàng.",
    rules: ["Chú ý vị trí sắp xếp: 'arranged in rows', 'placed on top of'."],
    vocabBag: [{ word: "stacked", ipa: "/stækt/", meaning: "Được xếp chồng gọn gàng" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[1]],
  },
];

export const INITIAL_PART2_LEVELS: LevelCategoryCardData[] = [
  {
    id: "p2-l1",
    part: "Part 2",
    type: "level",
    title: "Lv.1 Dưới 200",
    targetLevel: "Dưới 200",
    totalQuestions: 174,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Các câu hỏi trực tiếp Wh-questions đơn giản (Who, Where, When) có đáp án rõ ràng trực diện.",
    rules: ["Who -> Tên người/chức danh; Where -> Địa điểm; When -> Mốc thời gian."],
    vocabBag: [{ word: "tomorrow", ipa: "/təˈmɔːroʊ/", meaning: "Ngày mai" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[2]],
  },
  {
    id: "p2-l2",
    part: "Part 2",
    type: "level",
    title: "Lv.2 200–500",
    targetLevel: "200–300",
    totalQuestions: 154,
    completedQuestions: 1,
    correctCount: 1,
    wrongCount: 0,
    status: "Đang học",
    theorySummary: "Câu hỏi Why, How và câu hỏi Yes/No có trợ động từ cơ bản (Do, Does, Did, Is, Are).",
    rules: ["Why -> Lý do (Because, due to hoặc đưa ra giải thích hoàn cảnh)."],
    vocabBag: [{ word: "cancelled", ipa: "/ˈkænsld/", meaning: "Đã bị hủy bỏ" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[3]],
  },
  {
    id: "p2-l3",
    part: "Part 2",
    type: "level",
    title: "Lv.3 500–750",
    targetLevel: "300–400",
    totalQuestions: 347,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Câu hỏi lựa chọn Or, câu hỏi phủ định (Didn't you...), câu hỏi đuôi (Tag questions) và câu trần thuật.",
    rules: ["Không trả lời Yes/No cho câu hỏi Or."],
    vocabBag: [{ word: "either", ipa: "/ˈaɪðər/", meaning: "Cái nào trong hai cái cũng được" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[2]],
  },
  {
    id: "p2-l4",
    part: "Part 2",
    type: "level",
    title: "Lv.4 750–990",
    targetLevel: "400–495",
    totalQuestions: 75,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Câu trả lời gián tiếp cực kỳ khó: trả lời bằng một câu hỏi khác, người nói không biết, hoặc từ chối lịch sự.",
    rules: ["Câu trả lời không trực tiếp: 'I have no idea', 'Check with Mr. Davis' thường là đáp án đúng."],
    vocabBag: [{ word: "itinerary", ipa: "/aɪˈtɪnəreri/", meaning: "Lịch trình chuyến đi" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[3]],
  },
];

export const INITIAL_PART2_CATEGORIES: LevelCategoryCardData[] = [
  {
    id: "p2-c1",
    part: "Part 2",
    type: "category",
    title: "Câu hỏi Wh- (Who, Where, When)",
    totalQuestions: 54,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Các câu hỏi hỏi thông tin trực tiếp về Người, Địa điểm, Thời gian.",
    rules: ["Who -> Tên người/chức danh; Where -> Địa điểm; When -> Mốc thời gian."],
    vocabBag: [{ word: "tomorrow", ipa: "/təˈmɔːroʊ/", meaning: "Ngày mai" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[2]],
  },
  {
    id: "p2-c2",
    part: "Part 2",
    type: "category",
    title: "Câu hỏi Why & How",
    totalQuestions: 48,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hỏi lý do (Why) và cách thức/phương tiện/số lượng (How).",
    rules: ["Why -> Because / Due to; How -> Phương tiện hoặc cách thực hiện."],
    vocabBag: [{ word: "cancelled", ipa: "/ˈkænsld/", meaning: "Đã bị hủy" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[3]],
  },
  {
    id: "p2-c3",
    part: "Part 2",
    type: "category",
    title: "Câu hỏi Yes/No & Trợ động từ",
    totalQuestions: 62,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Câu hỏi bắt đầu bằng Do/Does/Did/Have/Has/Is/Are.",
    rules: ["Chú ý thì của câu hỏi và đại từ xưng hô trong câu trả lời."],
    vocabBag: [{ word: "available", ipa: "/əˈveɪləbl/", meaning: "Có sẵn / Rảnh" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[2]],
  },
  {
    id: "p2-c4",
    part: "Part 2",
    type: "category",
    title: "Câu bẫy & Trả lời gián tiếp",
    totalQuestions: 45,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Câu trả lời không chứa thông tin trực diện mà giải thích ngữ cảnh.",
    rules: ["Các câu trả lời kiểu 'I have no idea', 'Check with Mr. Davis' thường đúng."],
    vocabBag: [{ word: "itinerary", ipa: "/aɪˈtɪnəreri/", meaning: "Lịch trình" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[3]],
  },
];

export const INITIAL_PART3_LEVELS: LevelCategoryCardData[] = [
  {
    id: "p3-l1",
    part: "Part 3",
    type: "level",
    title: "Lv.1 Dưới 200",
    totalQuestions: 50,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại 2 người với câu hỏi nghe từ khóa trực diện trong câu đầu tiên.",
    rules: ["Đọc lướt 3 câu hỏi trước khi audio bắt đầu."],
    vocabBag: [{ word: "reception", ipa: "/rɪˈsepʃn/", meaning: "Quầy lễ tân" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "p3-l2",
    part: "Part 3",
    type: "level",
    title: "Lv.2 200–500",
    totalQuestions: 80,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại công sở về đặt vé, giao hàng, đổi lịch họp.",
    rules: ["Để ý ai nói gì (man vs woman)."],
    vocabBag: [{ word: "reschedule", ipa: "/ˌriːˈskedʒuːl/", meaning: "Đổi lại lịch trình" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "p3-l3",
    part: "Part 3",
    type: "level",
    title: "Lv.3 500–750",
    totalQuestions: 110,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại 3 người và câu hỏi suy luận ngụ ý câu nói.",
    rules: ["Câu hỏi 'What does the speaker imply' đòi hỏi hiểu ngữ cảnh."],
    vocabBag: [{ word: "feasibility", ipa: "/ˌfiːzəˈbɪləti/", meaning: "Tính khả thi" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "p3-l4",
    part: "Part 3",
    type: "level",
    title: "Lv.4 750–990",
    totalQuestions: 60,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại kết hợp sơ đồ, bản đồ và biểu đồ hình ảnh (Graphics).",
    rules: ["Nhìn thông tin trên biểu đồ và nghe dữ kiện đối chiếu."],
    vocabBag: [{ word: "discrepancy", ipa: "/dɪˈskrepənsi/", meaning: "Sự sai khác số liệu" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
];

export const INITIAL_PART3_CATEGORIES: LevelCategoryCardData[] = [
  {
    id: "p3-c1",
    part: "Part 3",
    type: "category",
    title: "Công sở & Văn phòng",
    totalQuestions: 42,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại thảo luận dự án, họp hành, phân công công việc.",
    rules: ["Lắng nghe tên dự án và thời hạn hoàn thành."],
    vocabBag: [{ word: "deadline", ipa: "/ˈdedlaɪn/", meaning: "Hạn chót" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "p3-c2",
    part: "Part 3",
    type: "category",
    title: "Dịch vụ & Đặt hàng",
    totalQuestions: 38,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại mua sắm, đặt bàn nhà hàng, đổi trả hàng hóa.",
    rules: ["Để ý lý do khách hàng gọi và phương án giải quyết."],
    vocabBag: [{ word: "refund", ipa: "/ˈriːfʌnd/", meaning: "Hoàn tiền" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "p3-c3",
    part: "Part 3",
    type: "category",
    title: "Hội thoại 3 người",
    totalQuestions: 28,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Cần phân biệt giọng nói của 3 nhân vật khác nhau.",
    rules: ["Nhận diện giọng nam 1, giọng nam 2 hoặc giọng nữ."],
    vocabBag: [{ word: "collaboration", ipa: "/kəˌlæbəˈreɪʃn/", meaning: "Sự hợp tác" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
  {
    id: "p3-c4",
    part: "Part 3",
    type: "category",
    title: "Hội thoại kèm Biểu đồ / Sơ đồ",
    totalQuestions: 30,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Hội thoại có hình ảnh đính kèm (sơ đồ chỗ ngồi, hóa đơn, lịch trình).",
    rules: ["Nhìn nhanh hình ảnh trước khi nghe audio đối chiếu."],
    vocabBag: [{ word: "chart", ipa: "/tʃɑːrt/", meaning: "Biểu đồ" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[4], SAMPLE_DICTATION_QUESTIONS[5], SAMPLE_DICTATION_QUESTIONS[6]],
  },
];

export const INITIAL_PART4_LEVELS: LevelCategoryCardData[] = [
  {
    id: "p4-l1",
    part: "Part 4",
    type: "level",
    title: "Lv.1 Dưới 200",
    totalQuestions: 40,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Các bài thông báo đơn giản tại ga tàu, sân bay và siêu thị.",
    rules: ["Nghe câu đầu tiên để biết bài nói diễn ra ở đâu."],
    vocabBag: [{ word: "passengers", ipa: "/ˈpæsɪndʒərz/", meaning: "Hành khách" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  {
    id: "p4-l2",
    part: "Part 4",
    type: "level",
    title: "Lv.2 200–500",
    totalQuestions: 65,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Tin nhắn thoại để lại qua điện thoại và thông báo nội bộ công ty.",
    rules: ["Xác định mục đích gọi điện ('I'm calling to...')."],
    vocabBag: [{ word: "inquire", ipa: "/ɪnˈkwaɪər/", meaning: "Hỏi thăm thông tin" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  {
    id: "p4-l3",
    part: "Part 4",
    type: "level",
    title: "Lv.3 500–750",
    totalQuestions: 90,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Bản tin thời tiết, tin tức tài chính và quảng cáo thương mại.",
    rules: ["Để ý các con số, dự báo thời tiết và chương trình khuyến mãi."],
    vocabBag: [{ word: "forecast", ipa: "/ˈfɔːrkæst/", meaning: "Dự báo thời tiết" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  {
    id: "p4-l4",
    part: "Part 4",
    type: "level",
    title: "Lv.4 750–990",
    totalQuestions: 50,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Bài phát biểu giới thiệu nhân vật và bài nói kết hợp biểu đồ hình ảnh.",
    rules: ["Kết hợp nghe và dò thông tin trên bảng biểu song song."],
    vocabBag: [{ word: "accolades", ipa: "/ˈækəleɪdz/", meaning: "Giải thưởng vinh danh" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
];

export const INITIAL_PART4_CATEGORIES: LevelCategoryCardData[] = [
  {
    id: "p4-c1",
    part: "Part 4",
    type: "category",
    title: "Thông báo công cộng & Ga tàu",
    totalQuestions: 35,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Bài phát thanh tại sân bay, ga tàu, siêu thị, triển lãm.",
    rules: ["Nghe câu đầu tiên để xác định địa điểm bài nói."],
    vocabBag: [{ word: "departure", ipa: "/dɪˈpɑːrtʃər/", meaning: "Chuyến khởi hành" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  {
    id: "p4-c2",
    part: "Part 4",
    type: "category",
    title: "Tin nhắn thoại & Điện thoại",
    totalQuestions: 40,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Lời nhắn để lại trong hộp thư thoại công việc.",
    rules: ["Xác định lý do người nói để lại lời nhắn ('I am calling to...')."],
    vocabBag: [{ word: "voicemail", ipa: "/ˈvɔɪsmeɪl/", meaning: "Hộp thư thoại" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  {
    id: "p4-c3",
    part: "Part 4",
    type: "category",
    title: "Tin tức & Dự báo thời tiết",
    totalQuestions: 25,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Bản tin phát thanh về giao thông, thời tiết, kinh tế.",
    rules: ["Ghi nhớ số liệu và danh từ chỉ khu vực."],
    vocabBag: [{ word: "traffic", ipa: "/ˈtræfɪk/", meaning: "Giao thông" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
  {
    id: "p4-c4",
    part: "Part 4",
    type: "category",
    title: "Bài phát biểu & Hướng dẫn",
    totalQuestions: 32,
    completedQuestions: 0,
    correctCount: 0,
    wrongCount: 0,
    status: "Chưa luyện tập",
    theorySummary: "Lời giới thiệu diễn giả, bài phát biểu khai mạc hội thảo.",
    rules: ["Chú ý tên diễn giả và chủ đề hội thảo."],
    vocabBag: [{ word: "keynote", ipa: "/ˈkiːnoʊt/", meaning: "Bài phát biểu chủ đề chính" }],
    questions: [SAMPLE_DICTATION_QUESTIONS[7], SAMPLE_DICTATION_QUESTIONS[8], SAMPLE_DICTATION_QUESTIONS[9]],
  },
];
