import { WordItem, TestItem } from "./types";

export const SAMPLE_WORDS: WordItem[] = [
  {
    id: "w-1",
    word: "negotiate",
    ipa: "/nəˈɡoʊʃieɪt/",
    partOfSpeech: "Verb",
    meaning: "Đàm phán, thương lượng hợp đồng hoặc thỏa thuận thương mại",
    example: "The executive team successfully negotiated a lucrative distribution agreement.",
    exampleMeaning: "Ban điều hành đã thương lượng thành công một thỏa thuận phân phối có lợi nhuận cao.",
    level: "B2",
    starred: true,
  },
  {
    id: "w-2",
    word: "invoice",
    ipa: "/ˈɪnvɔɪs/",
    partOfSpeech: "Noun",
    meaning: "Hóa đơn thanh toán hàng hóa hoặc dịch vụ",
    example: "All invoices must be submitted to the finance department by the end of each month.",
    exampleMeaning: "Tất cả hóa đơn phải được nộp cho bộ phận tài chính vào cuối mỗi tháng.",
    level: "B1",
  },
  {
    id: "w-3",
    word: "implement",
    ipa: "/ˈɪmplɪment/",
    partOfSpeech: "Verb",
    meaning: "Triển khai, thực thi chính sách hoặc quy trình mới",
    example: "We plan to implement the revised safety protocol starting next Monday.",
    exampleMeaning: "Chúng tôi dự định thực thi quy trình an toàn đã sửa đổi bắt đầu từ thứ Hai tuần tới.",
    level: "B2",
  },
  {
    id: "w-4",
    word: "itinerary",
    ipa: "/aɪˈtɪnəreri/",
    partOfSpeech: "Noun",
    meaning: "Lịch trình chi tiết chuyến đi công tác hoặc hội nghị",
    example: "The corporate travel coordinator emailed the complete flight itinerary to the delegate.",
    exampleMeaning: "Điều phối viên du lịch công ty đã gửi email lịch trình chuyến bay đầy đủ cho đại biểu.",
    level: "B1",
  },
  {
    id: "w-5",
    word: "warranty",
    ipa: "/ˈwɔːrənti/",
    partOfSpeech: "Noun",
    meaning: "Phiếu bảo hành hoặc cam kết chất lượng sản phẩm",
    example: "The commercial air conditioner is covered by an extensive three-year warranty.",
    exampleMeaning: "Máy điều hòa thương mại được bảo hành toàn diện trong vòng ba năm.",
    level: "B1",
    starred: true,
  },
  {
    id: "w-6",
    word: "collaborate",
    ipa: "/kəˈlæbəreɪt/",
    partOfSpeech: "Verb",
    meaning: "Hợp tác, cùng làm việc trong dự án",
    example: "Engineers from both branches collaborated on developing the AI engine.",
    exampleMeaning: "Các kỹ sư từ cả hai chi nhánh đã hợp tác phát triển động cơ AI.",
    level: "B2",
  },
  {
    id: "w-7",
    word: "revenue",
    ipa: "/ˈrevənuː/",
    partOfSpeech: "Noun",
    meaning: "Tổng doanh thu, nguồn thu nhập doanh nghiệp",
    example: "Online marketing efforts resulted in a 25% increase in total quarterly revenue.",
    exampleMeaning: "Các nỗ lực tiếp thị trực tuyến đã mang lại mức tăng 25% tổng doanh thu hàng quý.",
    level: "B2",
  },
  {
    id: "w-8",
    word: "recruit",
    ipa: "/rɪˈkruːt/",
    partOfSpeech: "Verb",
    meaning: "Tuyển dụng nhân sự mới cho cơ quan tổ chức",
    example: "The human resources manager hopes to recruit talented front-end developers.",
    exampleMeaning: "Trưởng phòng nhân sự hy vọng tuyển dụng được các lập trình viên front-end tài năng.",
    level: "B1",
  },
];

export const INITIAL_TESTS: TestItem[] = [
  // 10 Tests cho năm 2026
  { id: "test-2026-1", year: "2026", title: "Test 1", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-2", year: "2026", title: "Test 2", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-3", year: "2026", title: "Test 3", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-4", year: "2026", title: "Test 4", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-5", year: "2026", title: "Test 5", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-6", year: "2026", title: "Test 6", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-7", year: "2026", title: "Test 7", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-8", year: "2026", title: "Test 8", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-9", year: "2026", title: "Test 9", wordCount: 160, category: "2026", words: SAMPLE_WORDS },
  { id: "test-2026-10", year: "2026", title: "Test 10", wordCount: 160, category: "2026", words: SAMPLE_WORDS },

  // Bộ 600 Essential Words
  { id: "essential-1", year: "Essential", title: "Contracts (Hợp đồng)", wordCount: 12, category: "600_essential", words: SAMPLE_WORDS },
  { id: "essential-2", year: "Essential", title: "Marketing (Tiếp thị)", wordCount: 12, category: "600_essential", words: SAMPLE_WORDS },
  { id: "essential-3", year: "Essential", title: "Warranties (Bảo hành)", wordCount: 12, category: "600_essential", words: SAMPLE_WORDS },
  { id: "essential-4", year: "Essential", title: "Office Equipment", wordCount: 12, category: "600_essential", words: SAMPLE_WORDS },
  { id: "essential-5", year: "Essential", title: "Human Resources", wordCount: 12, category: "600_essential", words: SAMPLE_WORDS },
  { id: "essential-6", year: "Essential", title: "Financial Reports", wordCount: 12, category: "600_essential", words: SAMPLE_WORDS },

  // Bộ 2023
  { id: "test-2023-1", year: "2023", title: "Test 1 (ETS 2023)", wordCount: 150, category: "2023", words: SAMPLE_WORDS },
  { id: "test-2023-2", year: "2023", title: "Test 2 (ETS 2023)", wordCount: 150, category: "2023", words: SAMPLE_WORDS },
  { id: "test-2023-3", year: "2023", title: "Test 3 (ETS 2023)", wordCount: 150, category: "2023", words: SAMPLE_WORDS },
  { id: "test-2023-4", year: "2023", title: "Test 4 (ETS 2023)", wordCount: 150, category: "2023", words: SAMPLE_WORDS },
];
